name: Auto Commit from ChatGPT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto Commit
        run: |
          echo "✅ ChatGPT deployed at $(date)" >> deploy-log.txt
          git config --global user.name "ChatGPT Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:sha93-dev/Sha-s-chatbot-.git
          git add .
          git commit -m "Auto-deploy from ChatGPT"
          git push origin main
